# Generated by Django 2.1.2 on 2018-12-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('price', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('category', models.TextField()),
            ],
            options={
                'db_table': 'business',
                'managed': False,
            },
        ),
    ]
